Feat/duplicate
WildCodeSchool/reims-0320-js-github-fighters pull request #18
Opened 2020-04-27 14:29 UTC by brithe00

2020-04-27 15:24 UTC, rocambille requested changes

2020-04-27 15:24 UTC, wasthishelpful commented on src/components/SearchFighter.jsx
> +    <>{label}</>
maybe use a <label> for your label ;)

2020-04-28 08:42 UTC, brithe00 commented
Like that ?

2020-04-28 08:45 UTC, wasthishelpful commented
this should be improved: e.g. the label should be linked to a control (input, select, textarea) using htmlFor

but that's it :)

2020-04-28 08:45 UTC, merged

2020-04-28 08:50 UTC, brithe00 commented
Ok, I see, it can be improved with this for example :

`<label htmlFor="fighterInput">Fighter :</label>`

2020-04-28 08:53 UTC, wasthishelpful commented
yes, but you will need something identified as fighterInput. something like that:

    <label htmlFor="fighterInput">Fighter :</label>
    <input id="fighterInput" />